[package]
name = "ggcat-logging"
version = "2.0.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"


[features]
detailed-stats = []
